"""Write docs/coverage_snapshot.md and docs/sport_name_review.md from the current DuckDB build.

    python ingestion/export_coverage_report.py          (or: make report)

Both are snapshots; the live source of truth is MARTS.MART_SPORT_GAPS.
"""
from __future__ import annotations

import csv
import sys
from datetime import date
from pathlib import Path

import duckdb

# Hand-written notes for sports whose NAME may need a human check. Keyed by the name on the sheet.
NAME_NOTES = {
    "Frescoball": "Common spelling is 'Frescobol' (alias added)",
    "Kadima": "Also known as Matkot, Smashball, Raketa (aliases added)",
    "Touchtennis": "Only 1 OpenStreetMap use, inside a multi-sport tag",
    "Miniten Thug": "Possible stray word in the name - please check",
    "Pitton": "I could not verify this name - please check the spelling",
    "Biraq": "I could not verify this spelling - please check",
    "Qianball": "Transliterated name - please check the spelling",
    "Ketball": "I could not verify this name - please check the spelling",
}


def main() -> None:
    sys.stdout.reconfigure(encoding="utf-8")
    con = duckdb.connect("courtconnect.duckdb", read_only=True)
    today = date.today().isoformat()

    rows = con.sql("""
        select sport_name, coverage_status, venues_found, courts_found, has_osm_tag, recommended_next_source
        from marts.mart_sport_gaps
        order by case coverage_status when 'covered' then 1 when 'sparse' then 2 when 'tagged_none_found' then 3 else 4 end,
                 courts_found desc, sport_name""").fetchall()
    tot = con.sql("""select (select count(*) from core.dim_court), (select count(*) from core.dim_venue),
                            (select count(*) from core.dim_venue where name_source <> 'unnamed'),
                            (select count(*) from core.dim_venue where name_source in ('court_name', 'operator'))""").fetchone()
    surf = con.sql("select surface_type, count(*) from core.dim_court where record_kind='court' group by 1 order by 2 desc").fetchall()
    sett = con.sql("select setting, count(*) from core.dim_court group by 1 order by 2 desc").fetchall()
    status: dict[str, int] = {}
    for r in rows:
        status[r[1]] = status.get(r[1], 0) + 1

    L = [f"# California coverage snapshot ({today})\n",
         "Generated by `ingestion/export_coverage_report.py` from `marts.mart_sport_gaps`. Live numbers: query that table "
         "(DuckDB, or Snowflake `MARTS.MART_SPORT_GAPS`).\n",
         f"**{tot[0]:,} OSM court/facility records -> {tot[1]:,} venues. {tot[2]:,} venues have a name, but only {tot[3]:,} are "
         "confirmed names (tagged on the court or its operator); the rest are inferred from the park, school or club the court sits inside.**\n",
         "Sports by status: " + ", ".join(f"**{k}** {v}" for k, v in status.items()) + ".\n",
         "## Every racket sport on the master sheet\n",
         "| Sport | Status | Venues | Courts | Next source if not covered |", "|---|---|---:|---:|---|"]
    for n, s, v, k, _t, rec in rows:
        L.append(f"| {n} | {s} | {v} | {k} | {'' if s == 'covered' else rec} |")
    L += ["\n## Surfaces and indoor/outdoor: what the data can and cannot say\n",
          "Court records by playing surface: " + ", ".join(f"{a} {b:,}" for a, b in surf) + ".\n",
          "Court records by setting: " + ", ".join(f"{a} {b:,}" for a, b in sett) + ".\n",
          """**Read this before using the surface or indoor filters.**
- Most OpenStreetMap courts have **no surface tag**, so "unknown" is the biggest bucket. Clay, grass and sand courts exist,
  but only a handful are tagged as such.
- `likely_outdoor` means the court is an untagged outdoor pitch. It is an assumption, not data. Only `outdoor`, `indoor` and
  `covered` come from an explicit tag.
- Indoor courts are mostly mapped as buildings or sports centres, not as individual courts, so indoor court counts are low.
- Beach / sand courts are almost unmapped (a few courts statewide). Beach tennis and sandball need another source.

Filling these gaps needs a second source (Google Places, club and league directories). See `docs/decisions/0004`.
"""]
    Path("docs/coverage_snapshot.md").write_text("\n".join(L), encoding="utf-8", newline="")

    with open("transform/seeds/all_racquet.csv", encoding="utf-8", newline="") as f:
        sheet = list(csv.DictReader(f))
    mapped = {r["sport"] for r in csv.DictReader(open("transform/seeds/osm_sport_map.csv", encoding="utf-8", newline=""))}
    unmapped = [r for r in sheet if r["sport"].strip() not in mapped]
    R = [f"# Sport name review ({today})\n",
         f"The master list (`all_racquet`, synced from the Google Sheet) has {len(sheet)} racket sports. OpenStreetMap (our first "
         f"court source) has a tag for **{len(sheet) - len(unmapped)}** of them. These are the **{len(unmapped)} that are not on the sport map**, and why.\n",
         "**How to read it.** \"No OpenStreetMap tag exists\" means the sport is real but nobody has a way to map its courts there, so we "
         "need another source (Google Places keyword search, club directories, governing-body sites). It does **not** mean your "
         "spelling is wrong. Rows that say \"please check\" are names I could not verify.\n",
         "If a sport goes by another name, add it to `transform/seeds/sport_aliases.csv`; the Places / directory searches will use it.\n",
         "| # | Sport | Players | Why it is not on the map |", "|---|---|---|---|"]
    for i, r in enumerate(unmapped, 1):
        s = r["sport"].strip()
        note = NAME_NOTES.get(s) or "No OpenStreetMap tag exists" + ("" if r["url"] else " and no website listed")
        R.append(f"| {i} | {s} | {r['players'] or '-'} | {note} |")
    Path("docs/sport_name_review.md").write_text("\n".join(R) + "\n", encoding="utf-8", newline="")
    print(f"Wrote docs/coverage_snapshot.md ({len(rows)} sports) and docs/sport_name_review.md ({len(unmapped)} unmapped)")


if __name__ == "__main__":
    main()
