-- Run once in a Snowsight worksheet as ACCOUNTADMIN.
-- Creates an isolated dev environment with a hard cost cap (free-trial friendly).

USE ROLE ACCOUNTADMIN;

CREATE RESOURCE MONITOR IF NOT EXISTS COURTCONNECT_RM
  WITH CREDIT_QUOTA = 10
  TRIGGERS ON 80 PERCENT DO NOTIFY
           ON 100 PERCENT DO SUSPEND;

CREATE WAREHOUSE IF NOT EXISTS COURTCONNECT_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  RESOURCE_MONITOR = COURTCONNECT_RM;

CREATE DATABASE IF NOT EXISTS COURTCONNECT;

-- Least-privilege role used by dbt and the loader (not ACCOUNTADMIN).
CREATE ROLE IF NOT EXISTS COURTCONNECT_DEV;
GRANT USAGE ON WAREHOUSE COURTCONNECT_WH TO ROLE COURTCONNECT_DEV;
GRANT ALL ON DATABASE COURTCONNECT TO ROLE COURTCONNECT_DEV;
GRANT ALL ON ALL SCHEMAS IN DATABASE COURTCONNECT TO ROLE COURTCONNECT_DEV;
GRANT CREATE SCHEMA ON DATABASE COURTCONNECT TO ROLE COURTCONNECT_DEV;

-- Replace with your Snowflake username:
-- GRANT ROLE COURTCONNECT_DEV TO USER <your_username>;
